export declare function booleanValue()  : void;
export declare function numberValue()   : void;
export declare function stringValue()   : void;
export declare function nullValue()     : void;
export declare function functionValue() : void;
export declare function arrayValue()    : void;
export declare function objectValue()   : void;
export declare function undefinedValue()    : void;
export declare function errorObjectValue()  : void;
